airbnb 중간 PR (html/css)
code-squad/javascript-airbnb-main pull request #30
Opened 2020-02-04 09:13 UTC by Hu2y

상단에 form부분 제외하고 아래부분 완료 하였습니다.

2020-02-05 05:22 UTC, crongro commented
@Hu2y  MASTER에 PR을 보내시면 안됩니다~

2020-02-05 05:28 UTC, crongro requested changes
몇가지 요구사항을 드려봅니다~

리뷰 참고해서 수정하시고, commit & push 하시면 PR에 반영될거에요.
질문은 댓글로 남겨주시고요.

2020-02-05 05:28 UTC, crongro commented on reset.css
> +.clearfix{*zoom:1;}
clearfix라는 건 언제 사용하는거에요?

2020-02-05 05:28 UTC, crongro commented on reset.css
> +@media only screen and (-webkit-min-device-pixel-ratio: 1.5),
@media 의 의미는 뭔가요?

2020-02-05 05:28 UTC, crongro commented on style.css
> +ul {
모든 UL태그에 이 스타일이 반영될테니,  좀더 구체적인 selector문법을 사용해보세요.

2020-02-05 05:28 UTC, crongro commented on style.css
> +li {
UL과 마찬가지로 LI도 구체적인 selector문법이 필요~

2020-02-05 05:28 UTC, crongro commented on style.css
> +  font-family: AppleSDGothicNeo;
font-family를 여기저기 많이 적용했는데요.
css에는 상속개념이 있으니 이부분을 이해하고 수정해보세요.

2020-02-05 05:28 UTC, crongro commented on style.css
> +.content_h3 {
content_h2와 contnet_h3 가 같은 내용을 포함하고 있는데 어떤 해결책이 필요할까요?

2020-02-05 05:28 UTC, crongro commented on reset.css
> +input[type=search]::-webkit-search-cancel-button,
-webkit 이 의미하는거에 대해서 댓글 설명해주세요.

2020-02-06 13:36 UTC, Hu2y commented on reset.css
> +.clearfix{*zoom:1;}
부모 요소가 자식 요소를 감싸고 있을 때, 자식 요소에게 float 형식을 적용하면 부모 요소가 자식 요소를 더 이상 감싸지 않게되고 높이 값을 파악하지 못하게 되는 버그가 발생합니다. 부모 요소의 높이 값이 0px로 출력되고, 전체적인 HTML 요소들이 뒤엉키게 됩니다.

`부모 요소가 다시 자식 요소를 감쌀 수 있게 float을 초기화(clear) 하여 버그를 고쳐주는(fix) 코드가 필요한데 이것을 clearfix라고 합니다.`

부모에 overflow: hidden, clear:both 같은 속성을 추가 해줄수있지만, 사용하는곳이 많다면 부모태그에 clearfix 클래스를 같이 추가해주면 빠르게 적용 할 수 있습니다.

2020-02-06 13:37 UTC, Hu2y commented on reset.css
> +@media only screen and (-webkit-min-device-pixel-ratio: 1.5),
반응형 웹을 위해 미디어 쿼리를 사용합니다.

`<link rel="stylesheet" media="screen and (max-width: 768px)" href="mystyle.css" />`
태그내에서 사용할수도있고

`@media screen and (max-width: 768px) { body { background-color: lightgreen; } }`
스타일 시트 내에서 적용할수도 있습니다.

2020-02-06 13:37 UTC, Hu2y commented on style.css
> +ul {
해당 영역의  ul에만 적용 되도록 코드 수정하였습니다.

2020-02-06 13:37 UTC, Hu2y commented on style.css
> +li {
해당 영역의  li에만 적용 되도록 코드 수정하였습니다.

2020-02-06 13:37 UTC, Hu2y commented on style.css
> +  font-family: AppleSDGothicNeo;
`font-family: inherit`
inherit : 부모 요소의 속성값을 상속받음

inherit을 사용하지 않아도 최상위 태그에 적용하면 아래 태그까지 같이 적용되어, 어떤경우에 inherit 속성이 사용되는지 궁금합니다

2020-02-06 13:37 UTC, Hu2y commented on style.css
> +.content_h3 {
하나의 태그로 합치고  content_h2와 contnet_h3의 내용을 h1, span, p태그 사용으로 나누었습니다.

2020-02-06 13:37 UTC, Hu2y commented on reset.css
> +input[type=search]::-webkit-search-cancel-button,
브라우저 마다 적용되는 css가 달라서, 크로싱 브라우저를 위해서 사용합니다.
접두어에 붙여 사용합니다.
`-webkit- : 구글, 사파리 브라우저에 적용
-moz- : 파이어폭스 브라우저에 적용
-ms- : 익스플로러에 적용, 보통 생략합니다.
-o- : 오페라 브라우저에 적용`

2020-02-11 02:32 UTC, crongro approved these changes
답변 잘 봤어요. 
머지합니다~!

2020-02-11 02:32 UTC, crongro commented on index.html
> +                <h1 class="margin-bottom-16px">에어비앤비와 함께하는 여행</h1>
보통 이름에 px까지 붙이진 않아요~
나중에 em처럼 다른 단위가 사용될 수도 있고요. 16이  15가 될 수도 있고요.

2020-02-11 02:32 UTC, crongro commented on index.html
> +                      <svg style="height:40px;width:40px;display:block;overflow:visible" viewBox="0 0 24 24" fill="#60B6B5" fill-opacity="0" stroke="#60B6B5" stroke-width="1" focusable="false" aria-h
여기에는 inline안하면 안되나요?

2020-02-11 02:32 UTC, crongro commented on style.css
> +  left: 100px !important;
important는 가급적 사용하지 않도록 하세요!
먼저 css 캐스케이딩과 상속을 이해하세요!

2020-02-11 02:32 UTC, merged