[wook & Gren] Step 10-2
code-squad/javascript-airbnb-main pull request #8
Opened 2019-05-30 05:33 UTC by fed-gren

CSS 작성 완료했습니다.
리뷰 부탁드립니다.

2019-05-30 05:36 UTC, fed-gren commented
배포 URL입니다.
https://fed-gren.github.io/airbnb-clone/

2019-05-30 12:07 UTC, crongro requested changes
코드가 간결하고 군더더기 없어서 좋네요.
잘 구현했습니다. 

자 시간이 있을거라 생각되고, 조금 수정해보세요.

2019-05-30 12:07 UTC, crongro commented on index.html
> +  <section class="header__container">
section을 어떻게 쓸지 애매하지만, layout구성부분을 section으로 모두 구성하는 건 그리 좋지 않아요.
header / main 으로 나누는 게 더 좋을 거 같아요.

2019-05-30 12:07 UTC, crongro commented on index.html
> +    <div class="header__bookForm">
구체적인 css classname은 좋은데, 이걸 좀더 줄이려면 bookForm이라고만 해도 될 거 같네요. 
bookForm이 또 있지는 않을 거 같고용.

2019-05-30 12:07 UTC, crongro commented on index.html
> +    <div class="review__contents">
review__contents 라는 css class는 없죠? 
모든 html tag에 css classname이 필요한 건 아니니까, style부여할 필요 없으면 만들지 마세요.

2019-05-30 12:07 UTC, crongro commented on index.html
> +  <section class="review__container">
review__container 도 
그냥 review 이렇게만 쓰고 container역할로 이해하고 적용할 수 있을거 같아요. 껍데기를 모두 다 container라는 이름을 이어서 붙이면 중복같아서요. 

차라리, container라는 css classname이 있고, 그 역할이 웹페이지 여기저기서 사용하는 layout크기를 지정하는 역할이면 좋을 거 같고요.

2019-05-30 12:07 UTC, crongro commented on index.html
> +    <div class="review__contentsItemList">
list라고 classname을 붙였는데요, 
그렇다면 UL 이나 OL을 사용해야죠.

2019-05-30 12:07 UTC, crongro commented on index.html
>        <form action="#" method="POST">
다양한 form 관련 태그를 잘 썼네요~ input/select 등 👍

2019-05-30 12:07 UTC, nigayo commented on index.css
> +.review__contentsTitle + div {
형제를 가리키는 selector를 잘 썼어요.
그런데 DOM 구조에 의존성이 많은 css selector는 dom구조가 변경되면 깨질 수 있어서 좀 조심스럽게 사용하세요.

2019-05-30 12:07 UTC, nigayo commented on index.css
> +  margin-top: 1rem;
rem 과 em의 차이는 공부할 필요가 있습니다.

2019-05-30 12:07 UTC, nigayo commented on index.css
> +  border: 1px solid #ff5a60;
반복적인 value가 있다면, css variables 이라는 거 찾아서 적용해보세요.

2019-05-30 12:07 UTC, nigayo commented on index.css
> +  display: flex;
flex좋죠. 
거침없이 많이 사용하면서 익혀보세요.

2019-05-30 12:07 UTC, nigayo commented on index.css
> +  background-size: 100% 100%;
반응형이면 배경이미지 크기 설정하기 어렵더라고요.
background-size : cover 값도 한번 적용해보세요.

2019-06-10 06:05 UTC, fed-gren commented
리뷰해주신 내용 수정했습니다.

2019-06-10 06:30 UTC, crongro approved these changes
네 잘 수정했어요. 
머지해요~

2019-06-10 06:37 UTC, merged